public class VIConstant {



  public static final String PERIODE_FUTURE = '10 Future';
  public static final String PERIODE_PREOUVERTE = '15 Pré-ouverte';
  public static final String PERIODE_OUVERTE = '20 Ouverte';
  public static final String PERIODE_DERNIERE = '30 Dernière';    
  public static final String PERIODE_FERMEE = '90 Fermée';
    
  public static final String AFFAIRE_EN_COURS = '20 En cours';      

  public static final String AVENANT_PREVU = '10 Prévue';          
  public static final String AVENANT_EN_COURS = '20 En cours';      
    
  public static final String EC_BROUILLON ='10';
  public static final String EC_A_PRENDRE ='20';    
  public static final String EC_ENVOYEE ='30'; 
  public static final String EC_A_NE_PAS_ENVOYER ='40';    
  public static final String EC_GENEREE_A_NE_PAS_ENVOYER ='42';        
    
    
  public static final String EC_CA_AVENCEMENT ='Chiffre d affaires avancement';      
  public static final String EC_PROVISION_GARANTIE ='Provision Garantie';      
  public static final String EC_REPRISE_PROVISION_GARANTIE ='Reprise Provision Garantie';          
  public static final String EC_CA ='Chiffre d affaires';      
  public static final String EC_PROVISION_AMORTISSEMENT_AVCT ='Provision amortissement avct';        
  public static final String EC_PROVISION_FINANCEMENT_AVCT ='Provision financement avct';            
  public static final String EC_CA_SUR_AFFAIRE_EN_SAV ='Chiffre d affaires sur affaire cloturee';                
    
  public static final string TYPE_LIGNE_AFFAIRE_INITIAL = 'I';
  public static final string TYPE_LIGNE_AFFAIRE_GARANTIE = 'G';
    
  public static final integer DUREE_LOCATION = 12;  

    
}